# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Language
lang: es-ES

# Title
title: The Live Traveling
email: the.live.traveling@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  En este canal podrás encontrar diferentes viajes alrededor del mundo,
  algunos simplemente caminando, otros simplemente relajándose en algunos lugares,
  o tal vez conociendo la historia del lugar.
  
  Síguenos para descubrir el mundo desde tu TV/teléfono/PC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thelivetraveling.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon.png
twitter_username: thelivetraveling
github_username:  thelivetraveling

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# Build settings
theme: minima
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-feed
  - jekyll-maps
  - jekyll-youtube
  - jekyll-paginate

# The shortname for your Disqus site to enable comments.
disqus: thelivetraveling

# Colors
palette: blue
palettes:
  blue:
    sass:
      accent: '#2d72d9'
  green:
    sass:
      accent: '#00debc'
  orange:
    sass:
      accent: '#ff5000'

# Site footer
footer:
  content: "&copy; The Life Traveling all rights reserved 2025."
#  links:
#    - text: Instagram
#      url: 'https://www.instagram.com/thelivetraveling'
#      new_window: true
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'

# Permalinks
permalink: /:title
markdown: kramdown

# Sass
sass:
  verbose: true
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
